### ISSUE TITLE
ImageTextMultilineOutlined + Text Load Line From File

### ISSUE THREAD

**Issue by jgal14** [Nourepide/ComfyUI-Allor#16]
Hi there,

At the moment there doesn't appear to be a way to create multi-line text from a file (perhaps I'm missing an obvious solution).

Is it possible to add the ability to read \<br> in text, or to set an automatic line break feature at a set character / word / container width?

Thanks!

**Comment by Nourepide** [comment]
So you need a node that allows you to read text from a file?

And you also need a node that allows you to set a fixed width?

I apologize if I'm misunderstanding, I've been writing documentation all night and now it feels like my brain is literally drying up.

**Comment by Nourepide** [comment]
> On a separate note, one piece of feedback (or potentially user error) is that a useful feature on the image resize nodes would be a 'max height' or 'max width' - I.E resizing to a max height or width dimension whilst maintaining existing aspect ratio.

If it's not too much trouble here too it could use more details for my tired brain. 😅

I suppose it will take me not so much time to realize something with image resizing.

**Comment by jgal14** [comment]
Hey there,

Apologies I should have been clearer.

I have a node to load text from a file, however it loads a single line at a time from a txt file - Which means the multi-line text node only generates text in a single line (without any line breaks).

The goal is to be able to load a single line of text, and somehow set the line-break point.

I'm sure there are multiple ways to address this functionality.

My thoughts were;

- Recognise line break \<br> in the source text
- Set a line length limit before a line break is created (either character length, words or size).

Let me know if you would like further clarification.

Thanks

**Comment by Nourepide** [comment]
Okay, I think I'm starting to get it.

However, I do have a few questions:

Your node only reads one line from the file, does this mean that after concatenating the lines, the line break information is erased? Or is it iterated over the lines each queue?

**Comment by jgal14** [comment]
> > On a separate note, one piece of feedback (or potentially user error) is that a useful feature on the image resize nodes would be a 'max height' or 'max width' - I.E resizing to a max height or width dimension whilst maintaining existing aspect ratio.
> 
> If it's not too much trouble here too it could use more details for my tired brain. 😅
> 
> I suppose it will take me not so much time to realize something with image resizing.

Sure thing.

The 'constrain image' node [from here](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) contains the functionality I'm describing.

In the below example, I have set the max width to an arbirary ceiling (2000) and am controlling the output width of the image with the height (758). The output image maintains the aspect ratio of the original.

The use case here is to overlay the resized image onto another image (of which I know the dimensions), so having a max width / height limited allows for scaling the image to fit more easily. 

![image](https://github.com/Nourepide/ComfyUI-Allor/assets/81528787/3912f707-67e0-4e17-bbc4-30d7df7e9ccd)

I hope that description helps.

**Comment by jgal14** [comment]
> Okay, I think I'm starting to get it.
> 
> However, I do have a few questions:
> 
> Your node only reads one line from the file, does this mean that after concatenating the lines, the line break information is erased? Or is it iterated over the lines each queue?

The node only reads a single line, it doesn't offer a concatenate functionality.

I suppose using a concatenate node to combine lines before passing to the multi-line tool would be another way to solve this challenge!

Here is the node 

![image](https://github.com/Nourepide/ComfyUI-Allor/assets/81528787/4561bde2-d80a-4979-8e7b-f7e7c2debcb6)

I will test concatenating the text before feeding it into the multi-line node.

Thanks!

**Comment by Nourepide** [comment]
> The 'constrain image' node [from here](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) contains the functionality I'm describing...

So if I'm reading this right:

* You get images of unknown size as input.
* You expect the output to be images with height no greater than MAX_HEIGHT and width no greater than MAX_WIDTH.
* In case the image exceeds one of these values it will be scaled to the minimum size of these values
 
If I understand correctly, tomorrow I will make a node called ImageTransformResizeClip with this functionality.

**Comment by jgal14** [comment]
> > The 'constrain image' node [from here](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) contains the functionality I'm describing...
> 
> So if I'm reading this right:
> 
> * You get images of unknown size as input.
> * You expect the output to be images with height no greater than MAX_HEIGHT and width no greater than MAX_WIDTH.
> * In case the image exceeds one of these values it will be scaled to the minimum size of these values
> 
> If I understand correctly, tomorrow I will make a node called ImageTransformResizeClip with this functionality.

Yes, that sounds correct!

(just a caveat on the 3rd point, the output image must maintain it's original aspect ratio) 

Excellent, thank you very much for your support.

**Comment by jgal14** [comment]
> > The node only reads a single line, it doesn't offer a concatenate functionality.
> 
> Is this your personal node that you made yourself?
> 
> If so, wouldn't it be easier to make a separate node that just loads the text from the file completely and puts newline wildcards in it?
> 
> I can help you with that.

It isn't my own node, it's from the WAS node suite.

I'm just testing the concatenate solution, and it appears to be working - thank you for the offer of support.

I do think a more advanced 'line-break' / Text wrapping functionality would be useful for formatting text - For example if you have a focus image on a page which you want text to be wrapped around. I suspect that's a functionality of a completely different scope though!

**Comment by Nourepide** [comment]
What scope of functionality is not that important. If you need a node to help you with something, I will always find time to make it for you.

You just need to describe very precisely what you want and it will definitely be realized by me.

**Comment by jgal14** [comment]
> What scope of functionality is not that important. If you need a node to help you with something, I will always find time to make it for you.
> 
> You just need to describe very precisely what you want and it will definitely be realized by me.

Thank you for your support.

I don't have a fully formed idea of what the 'perfect' text formatting functionality might be yet - I will think about it.

One **very** useful functionality would be the ability to have static text with dynamic words that can be imported from a txt file.

For example;

The man's name was [index 1], he lived at [index 2]. His favourite sport was [index 3] and his favourite team was [index 4].

Is that sort of thing even possible?

**Comment by Nourepide** [comment]
> Is that sort of thing even possible?

Yes, of course. Especially after nodes in the Lens submodule I don't think it will be difficult [like this](https://github.com/Nourepide/ComfyUI-Allor/blob/6fd709b167e3d78887005c568f118949d1b80212/modules/ImageEffects.py#L234).

But node can really be as complex in design as it is simple. I propose to do a brainstorming, which usually helps me to design complex functionality.

1. **What problem does it solve?** - A brief description of what this node is for.
2. **What should it look like?** - Approximate input and output parameters.
3. **How should it work?** - Your idea of how the node should work.
4. **How should it be implemented?** - There is no point in answering this part, it's completely my task, I just wrote it to tell you about my approach.

I suggest to start with the first question and the general picture will start to emerge.

**Comment by Nourepide** [comment]
Node ImageTransformResizeClip was implemented in 4c6099c.

Documentation - [Resize Clip](https://nourepide.github.io/ComfyUI-Allor-Doc/image-transform-resize-clip.html)

Example of work:

![image](https://github.com/Nourepide/ComfyUI-Allor/assets/22074527/c34b7b2a-df41-4863-a8d1-373b274fc5cf)

**Comment by jgal14** [comment]
> Node ImageTransformResizeClip was implemented in [4c6099c](https://github.com/Nourepide/ComfyUI-Allor/commit/4c6099c5768eaf42dd5d6de236bf75a2e58194d3).
> 
> Documentation - [Resize Clip](https://nourepide.github.io/ComfyUI-Allor-Doc/image-transform-resize-clip.html)
> 
> Example of work:
> 
> ![image](https://private-user-images.githubusercontent.com/22074527/286085288-c34b7b2a-df41-4863-a8d1-373b274fc5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzQ4ODMsIm5iZiI6MTcwMTE3NDU4MywicGF0aCI6Ii8yMjA3NDUyNy8yODYwODUyODgtYzM0YjdiMmEtZGY0MS00ODYzLWE4ZDEtMzczYjI3NGZjNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEyMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MmIyMWRkYjc0MDMxYWQ0ZDY5MmIyMjk2ZDdhMGEyMDc2MThkNWIwY2ExZGM1ODNhMmQzMGQ3NzQ4MDAyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ryMJPVXBVgbinfrQ3Tv-4tGHJLiR63GvipXrwkT5Ot0)

Fantastic, I will test this later in my workflow!

**Comment by Nourepide** [comment]
As a result, the node will take two text values.

* The first text value will contain parameters to populate the second text.
* The second text value will contain text with places that can be replaced.

In general, the work of this node will be similar to [printf](https://en.wikipedia.org/wiki/Printf) from the C language.

This node will be part of the new Text module in Allor 2 (which will include data proccesing), so we'll have to wait.

**Comment by jgal14** [comment]
> As a result, the node will take two text values.
> 
> * The first text value will contain parameters to populate the second text.
> * The second text value will contain text with places that can be replaced.
> 
> In general, the work of this node will be similar to [printf](https://en.wikipedia.org/wiki/Printf) from the C language.
> 
> This node will be part of the new Text module in Allor 2 (which will include data proccesing), so we'll have to wait.

Understood, thanks for the update!

On another note - Do you know of any models for the ImageSegmentation node that can segment just the head of a subject (without neck / upper body clothing)?

Thanks!

**Comment by Nourepide** [comment]
Hmm, I don't recall there being anything similar among the ONNX models.

However, there are "true" Image Segmentation models on Hugging Face that split images into multiple parts with a description of each part.

Among them there is actually one model that splits the head into several parts, including - face, eyes, ears, etc.

There are also models that find an object by its description.

None of this is supported yet, because ImageSegmentation node should actually be called ImageSegmentationRembg or ImageSegmentationOnnx.

I think it would be good to completely redesign the ImageSegmentation module in Allor 2.

**Comment by jgal14** [comment]
> Hmm, I don't recall there being anything similar among the ONNX models.
> 
> However, there are "true" Image Segmentation models on Hugging Face that split images into multiple parts with a description of each part.
> 
> Among them there is actually one model that splits the head into several parts, including - face, eyes, ears, etc.
> 
> There are also models that find an object by its description.
> 
> None of this is supported yet, because ImageSegmentation node should actually be called ImageSegmentationRembg or ImageSegmentationOnnx.
> 
> I think it would be good to completely redesign the ImageSegmentation module in Allor 2.

Thanks for the ideas!

I tracked down a some SAM image segmentation solutions and implemented them into my workflow, they seem to work well.

I had some further thoughts on text formatting functionality - Would you like me to open a new thread and note my ideas there?

**Comment by Nourepide** [comment]
> Would you like me to open a new thread and note my ideas there?

Uh, sure. Feel free to suggest any ideas.

**Comment by Nourepide** [comment]
> Is that sort of thing even possible?

Literally just finished finalising a similar function. It takes the text, finds the necessary key characters in it and modifies the text following these rules.

`frb` - Foreground Red Bright
`bgn` - Background Green Normal
`au` - Attribute Bold
`au` - Attribute Underline

This function will be used for the new logging system in Allor v.2.
![image](https://github.com/Nourepide/ComfyUI-Allor/assets/22074527/1f89cdaa-d045-42ae-b5d1-222df34b1515)
