### ISSUE TITLE
作者啊，你的插件为什么一更新就挂了，

### ISSUE THREAD

**Issue by cao1101** [Nourepide/ComfyUI-Allor#17]
D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.，出现C盘问题，我连C盘都没有

**Comment by cao1101** [comment]
> D:\a_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.，出现C盘问题，我连C盘都没有

是D盘

**Comment by Nourepide** [comment]
So I understand correctly that you can't run Allor because of this error, or it just appears every time you run it?

**Comment by cao1101** [comment]
So every time I repair it, it can be used normally. The repair method is to uninstall onnxruntime-gpu, and then uninstall onnxruntime. After the case, it can be used normally after installing onnxruntime. However, every time I upgrade my comfyui or restart it, the error will occur. The above error will pop up. This plug-in calls onnxruntime. So, is this error easy to fix?

**Comment by Nourepide** [comment]
It's not the first time I've gotten information that onnx is crooked on Windows systems, which is very strange since the developer of onnx is Microsoft.

I'm going to put ComfyUI on Windows today and see how it works there.

I also need more information: Windows version, video card and whether you have onnxruntime-gpu by default in requirements.txt or not

**Comment by Nourepide** [comment]
Also please check if ImageSegmentatoin node works at all when there is an error or if it doesn't affect the work.

**Comment by cao1101** [comment]
My Windows version is 11 64-bit, and my graphics card is the NVIDIA 3080 16GB version. My requirements.txt file describes the dependencies as follows: rembg, onnx.

If you want, you can install onnxruntime with GPU support
onnxruntime[gpu]
For Nvidia (only for GPU onnxruntime)
tensorrt
cuda-python
When there is a problem, the ImageSegmentation node completely fails to work, showing an error related to my D drive. However, my computer only has a C drive and no D drive. Other nodes work normally.

**Comment by cao1101** [comment]
The version on my computer should be about 15 days old. I replaced the latest one because of the issue we are discussing.

**Comment by cao1101** [comment]
Another important piece of information: my CUDA version is 12.3.

**Comment by Layer-norm** [comment]
@Nourepide Windows version is not the point. The environment installed with pytorch for CUDA 12 might cause this error. They have to complied onnxruntime-gpu manually to solve this promblem when they want to use [ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z](https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z) or other version with cu121 environment.

**Comment by Nourepide** [comment]
Can't reproduce after a few days of use with Windows - ComfyUI Portable.

Try reinstalling Allor using these instructions.

https://nourepide.github.io/ComfyUI-Allor-Doc/installation-allor.html

**Comment by cao1101** [comment]
Received. After testing, it seems that I did not install it in the correct way. Installing it in the way you recommended has solved the problem. The plug-in is very easy to use. Thank you.

**Comment by Nourepide** [comment]
If you encounter any further problems, feel free to reach out again.
