### ISSUE TITLE
ModuleNotFoundError: No module named 'custom_nodes.comfyui_allor'

### ISSUE THREAD

**Issue by kenyonxu** [Nourepide/ComfyUI-Allor#2]
![image](https://github.com/Nourepide/ComfyUI-Allore/assets/1241198/8d79075d-4619-416d-9843-2db639846cb4)

![image](https://github.com/Nourepide/ComfyUI-Allore/assets/1241198/3ea239c9-d806-4265-9ffa-1fb1584b0446)

**Comment by Nourepide** [comment]
It looks like there are problems only with Windows.
I will try during today/tomorrow to see why it works differently on another OS.

**Comment by ltdrdata** [comment]
https://github.com/Nourepide/ComfyUI-Allore/blob/73c2a024a810c2ec58e4ee910773d78665418b69/modules/ImageSegmentation.py#L6

This is  the problem.
You should not use "custom_nodes.comfyui_allor" this approach..

People changes directory name. And default your git repository name is **comfyui_allore**.
So the module name is incompatible with many people.

add ```os.path.abspath(__file__)``` in __init__.py 

and just use like this 

```session.CustomSession import CustomAbstractSession ```

**Comment by Nourepide** [comment]
> https://github.com/Nourepide/ComfyUI-Allore/blob/73c2a024a810c2ec58e4ee910773d78665418b69/modules/ImageSegmentation.py#L6
> 
> This is the problem. You should not use "custom_nodes.comfyui_allor" this approach..
> 
> People changes directory name. And default your git repository name is **comfyui_allore**. So the module name is incompatible with many people.
> 
> add `sys.path.append(os.path.abspath(__file__))` in `__init__.py `
> 
> and just use like this
> 
> `session.CustomSession import CustomAbstractSession `

I really changed the name of the repository and forgot about it.
I'll release a quick fix for now, then I'll do it normally.

**Comment by Nourepide** [comment]
Completely fixed in last [commit](https://github.com/Nourepide/ComfyUI-Allore/commit/90a3249c45ccdfe3ce50e9ea1c9b75a00227d3de).
