### ISSUE TITLE
how to fix this Attention？

### ISSUE THREAD

**Issue by Elminsst** [Nourepide/ComfyUI-Allor#27]
Attention! You are currently using an unstable fyb;main update branch.
         This branch is intended for the development of fmb;Allor v.2.

         Please be aware that changes made in fmb;Allor v.2 may disrupt your current workflow.
         Nodes may be renamed, parameters within them may be altered or even removed.

         If backward compatibility of your workflow is important to you, consider this.
         You can change the fcb;branch_name_param parameter to fbb;v1 in your fgb;config_json.

         If you are prepared for potential changes, you can modify your configuration file.
         To accept, switch the fcb;confirm_unstable_param parameter in your fgb;config_json to fbb;true.
         This will result in this warning no longer appearing.

 We appreciate your support and understanding during this transition period.
         Thank you and welcome to fmb;Allor v.2.

**Comment by Nourepide** [comment]
The text directly says how to disable it. Go to config.json and set the confirm_unstable value to true.
