### ISSUE TITLE
When loading the graph

### ISSUE THREAD

**Issue by robbigoal** [Nourepide/ComfyUI-Allor#5]
When loading the graph, the following node types were not found:
ImageScale
ImageBlur
Nodes that have failed to load will show as red on the graph.

is there something wrong?

**Comment by Nourepide** [comment]
Sorry for long answer.

Use `ImageTransformResizeAbsolute` and `ImageFilterBlur` instead.

**Comment by Nourepide** [comment]
Closed because 763eade.
